
import React, { useState, useRef, useEffect } from 'react';
import { Layers, Upload, RefreshCw, Download, Palette } from './Icons';
import { analyzeMoodboard } from '../services/geminiService';
import { showToast } from './Toast';

const MoodboardGenerator: React.FC = () => {
    const [image, setImage] = useState<string | null>(null);
    const [data, setData] = useState<any>(null);
    const [loading, setLoading] = useState(false);
    const [compositeUrl, setCompositeUrl] = useState<string | null>(null);
    const fileRef = useRef<HTMLInputElement>(null);

    const handleUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if(file) {
            const reader = new FileReader();
            reader.onload = () => {
                const imgStr = reader.result as string;
                setImage(imgStr);
                generateBoardData(imgStr);
            };
            reader.readAsDataURL(file);
        }
    };

    const generateBoardData = async (img: string) => {
        setLoading(true);
        setCompositeUrl(null);
        try {
            const res = await analyzeMoodboard([img]);
            setData(res);
            // Once data is ready, generate the composite image
            await renderComposite(img, res);
        } catch(e) {
            showToast("Analysis failed", "error");
        } finally {
            setLoading(false);
        }
    };

    const renderComposite = async (imgSrc: string, boardData: any) => {
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        if (!ctx) return;

        // Poster Size (Portrait)
        const W = 1080;
        const H = 1350;
        canvas.width = W;
        canvas.height = H;

        // Load Source Image
        const img = new Image();
        img.src = imgSrc;
        await new Promise((resolve) => { img.onload = resolve; });

        // 1. Background
        ctx.fillStyle = '#f5f5f5'; 
        ctx.fillRect(0, 0, W, H);

        // 2. Draw Main Image (Top 65%)
        const imgH = H * 0.65;
        // Cover fit
        const scale = Math.max(W / img.width, imgH / img.height);
        const x = (W / 2) - (img.width / 2) * scale;
        const y = (imgH / 2) - (img.height / 2) * scale;
        ctx.save();
        ctx.beginPath();
        ctx.rect(40, 40, W - 80, imgH - 40); // Margins
        ctx.clip();
        ctx.drawImage(img, x, y, img.width * scale, img.height * scale);
        ctx.restore();

        // 3. Typography Section (Bottom)
        const textStart = imgH + 60;
        
        // Theme Title
        ctx.fillStyle = '#1a1a1a';
        ctx.font = 'bold 80px "Inter", sans-serif';
        ctx.textAlign = 'left';
        ctx.fillText((boardData.theme || "Aesthetic").toUpperCase(), 50, textStart + 40);

        // Caption
        ctx.fillStyle = '#666666';
        ctx.font = 'italic 32px "Inter", serif';
        ctx.fillText(`"${boardData.caption || ''}"`, 50, textStart + 100);

        // 4. Color Palette (Circles)
        if (boardData.colors) {
            const circleY = H - 180;
            const radius = 50;
            const gap = 30;
            
            boardData.colors.forEach((color: string, i: number) => {
                const cx = 50 + radius + (i * (radius * 2 + gap));
                
                // Shadow
                ctx.save();
                ctx.shadowColor = 'rgba(0,0,0,0.2)';
                ctx.shadowBlur = 10;
                ctx.shadowOffsetY = 5;
                
                ctx.beginPath();
                ctx.arc(cx, circleY, radius, 0, Math.PI * 2);
                ctx.fillStyle = color;
                ctx.fill();
                ctx.restore();

                // Hex Text
                ctx.fillStyle = '#333';
                ctx.font = 'bold 20px monospace';
                ctx.textAlign = 'center';
                ctx.fillText(color, cx, circleY + radius + 30);
            });
        }

        // 5. Keywords (Pills)
        if (boardData.keywords) {
            const kwY = textStart + 160;
            let currentX = 50;
            ctx.font = '24px "Inter", sans-serif';
            
            boardData.keywords.slice(0, 4).forEach((kw: string) => {
                const textWidth = ctx.measureText(kw).width;
                const pillW = textWidth + 40;
                
                ctx.fillStyle = '#e0e0e0';
                ctx.beginPath();
                ctx.roundRect(currentX, kwY, pillW, 40, 20);
                ctx.fill();

                ctx.fillStyle = '#000';
                ctx.textAlign = 'center';
                ctx.fillText(kw, currentX + pillW/2, kwY + 28);

                currentX += pillW + 20;
            });
        }
        
        // Brand Footer
        ctx.fillStyle = '#999';
        ctx.font = '20px sans-serif';
        ctx.textAlign = 'right';
        ctx.fillText("Generated by SnapAura AI", W - 50, H - 40);

        setCompositeUrl(canvas.toDataURL('image/png'));
    };

    const downloadBoard = () => {
        if(!compositeUrl) return;
        const link = document.createElement('a');
        link.href = compositeUrl;
        link.download = `snapaura-moodboard-${Date.now()}.png`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        showToast("Moodboard Saved!", "success");
    };

    return (
        <div className="space-y-6 animate-fade-in-up">
            <div className="bg-[#292d3e] shadow-neu p-6 rounded-2xl">
                <div className="flex items-center gap-3 mb-6">
                    <div className="bg-[#292d3e] shadow-neu-pressed p-3 rounded-full text-pink-400"><Layers size={24} /></div>
                    <h2 className="text-xl font-bold text-gray-200">Moodboard AI</h2>
                </div>

                {!image ? (
                    <button onClick={() => fileRef.current?.click()} className="w-full h-40 bg-[#292d3e] shadow-neu active:shadow-neu-pressed rounded-xl flex flex-col items-center justify-center gap-2 text-gray-400 hover:text-pink-400 transition-all">
                        <Upload size={32} />
                        <span className="font-bold">Upload Inspiration Image</span>
                    </button>
                ) : (
                    <div className="space-y-6">
                        {/* Result Display */}
                        <div className="relative rounded-xl overflow-hidden shadow-neu bg-[#f5f5f5] group min-h-[300px] flex items-center justify-center">
                            {compositeUrl ? (
                                <img src={compositeUrl} className="w-full h-auto object-contain" alt="Moodboard" />
                            ) : (
                                <div className="flex flex-col items-center gap-3">
                                    <RefreshCw className="animate-spin text-pink-400" size={32} />
                                    <p className="text-sm text-gray-500 font-bold animate-pulse">Designing aesthetic...</p>
                                </div>
                            )}
                        </div>

                        {loading ? null : (
                            <div className="flex gap-4">
                                <button 
                                    onClick={downloadBoard}
                                    className="flex-1 bg-[#292d3e] text-pink-400 shadow-neu py-4 rounded-xl font-bold flex items-center justify-center gap-2 active:shadow-neu-pressed transition-all"
                                >
                                    <Download size={18} /> Download Moodboard
                                </button>
                                <button 
                                    onClick={() => {setImage(null); setData(null); setCompositeUrl(null);}} 
                                    className="p-4 bg-[#292d3e] shadow-neu rounded-xl text-gray-400 hover:text-white active:shadow-neu-pressed transition-all"
                                    title="New Board"
                                >
                                    <RefreshCw size={20} />
                                </button>
                            </div>
                        )}
                    </div>
                )}
            </div>
            <input type="file" ref={fileRef} onChange={handleUpload} className="hidden" />
        </div>
    );
};

export default MoodboardGenerator;
